### ISSUE TITLE
Bug by reloading in Browser

### ISSUE THREAD

**Issue by Fabiano197** [socketdown/M2B#5]
If u reload M2B in Browser the whole content is gone. If you delete the local storage cookie, the problem is gone, so  the bug has something to do with the cookie. Please fix it!!

**Comment by Fabiano197** [comment]
FEHLERCODE

angular.min.js:117 SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at b.$scope.loadLastUsedDecks (http://localhost:8000/js/mb.js:65:17)
    at new <anonymous> (http://localhost:8000/js/mb.js:78:10)
    at Object.invoke (http://localhost:8000/js/angular.min.js:41:372)
    at R.instance (http://localhost:8000/js/angular.min.js:89:203)
    at n (http://localhost:8000/js/angular.min.js:64:374)
    at g (http://localhost:8000/js/angular.min.js:58:305)
    at http://localhost:8000/js/angular.min.js:57:455
    at link (http://localhost:8000/js/angular.min.js:275:432)
    at ja (http://localhost:8000/js/angular.min.js:80:350) <div ng-include="'main.html'" class="ng-scope" data-ng-animate="1">(anonymous function) @ angular.min.js:117(anonymous function) @ angular.min.js:89ja @ angular.min.js:80n @ angular.min.js:66g @ angular.min.js:58(anonymous function) @ angular.min.js:57(anonymous function) @ angular.min.js:62d @ angular.min.js:59l @ angular.min.js:63(anonymous function) @ angular.min.js:274(anonymous function) @ angular.min.js:130$eval @ angular.min.js:144$digest @ angular.min.js:142$apply @ angular.min.js:145l @ angular.min.js:97H @ angular.min.js:101u.onload @ angular.min.js:102
cordova.js:1010 adding proxy for Battery
